---
- name: Listen for events on a webhook
  hosts: all

  ## Define our source for events

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5501

  ## Define the conditions we are looking for

  rules:
    - name: Say Hello
      condition: event.payload.message == "Ansible is super cool"

  ## Define the action we should take should the condition be met

      action:
        run_job_template:
          name: "Run Remediation Create Vlan"
          organization: "IMAPAC"
          controller_url: "https://tower.example.com/api/v2/job_templates/27"
          controller_username: "ansible_eda"
          controller_password: "123456"
          extra_vars:
            vlan_name: "{{ event.payload.vlan_name }}"
